version: 2
sphinx:
  configuration: source/conf.py

formats:
  - epub
  - pdf
  - htmlzip

submodules:
  include: all

build:
  os: ubuntu-22.04
  tools:
    python: "3.12"
  apt_packages:
    - fonts-noto
    - fonts-noto-color-emoji

python:
  install:
    - requirements: source/requirements.txt
    - method: pip
      path: .
